export class ComputeMesh{
  constructor({channel='him-compute-mesh',heartbeatMs=15000}={}){this.id=crypto.randomUUID();this.channelName=channel;this.heartbeatMs=heartbeatMs;this.peers=new Map();this.channel=null;this.timer=null;this.handlers=new Map();this.pending=new Map()}
  capabilities(){return {webgpu:Boolean(globalThis.navigator?.gpu),wasm:typeof WebAssembly!=='undefined',sharedMemory:typeof SharedArrayBuffer!=='undefined',hardwareConcurrency:globalThis.navigator?.hardwareConcurrency||1}}
  start(){if(typeof BroadcastChannel==='undefined')return this;this.channel=new BroadcastChannel(this.channelName);this.channel.onmessage=e=>this.receive(e.data);this.announce();this.timer=setInterval(()=>this.announce(),this.heartbeatMs);return this}
  stop(){clearInterval(this.timer);this.channel?.close();this.channel=null}
  announce(){this.channel?.postMessage({type:'peer',id:this.id,capabilities:this.capabilities(),at:Date.now()});this.prune()}
  register(kind,handler){this.handlers.set(kind,handler);return this}
  async submit(kind,payload,{timeoutMs=30000}={}){const id=crypto.randomUUID(),local={id:this.id,capabilities:this.capabilities(),handlers:[...this.handlers.keys()]},candidates=[local,...this.peers.values()].filter(p=>p.handlers?.includes(kind));const target=candidates.sort((a,b)=>Number(b.capabilities.webgpu)-Number(a.capabilities.webgpu)||b.capabilities.hardwareConcurrency-a.capabilities.hardwareConcurrency)[0];if(!target||target.id===this.id){const handler=this.handlers.get(kind);if(!handler)throw new Error(`no mesh handler for ${kind}`);return handler(payload)}return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error('mesh task timeout'))},timeoutMs);this.pending.set(id,{resolve,reject,timer});this.channel.postMessage({type:'task',id,kind,payload,target:target.id,source:this.id})})}
  async receive(message){if(!message||message.id===this.id)return;if(message.type==='peer'){this.peers.set(message.id,{...message,handlers:message.handlers||[]});this.channel?.postMessage({type:'handlers',id:this.id,handlers:[...this.handlers.keys()],capabilities:this.capabilities(),at:Date.now()})}else if(message.type==='handlers')this.peers.set(message.id,message);else if(message.type==='task'&&message.target===this.id){try{const result=await this.handlers.get(message.kind)?.(message.payload);this.channel.postMessage({type:'result',id:message.id,target:message.source,result})}catch(error){this.channel.postMessage({type:'result',id:message.id,target:message.source,error:error.message})}}else if(message.type==='result'&&message.target===this.id){const pending=this.pending.get(message.id);if(pending){clearTimeout(pending.timer);this.pending.delete(message.id);message.error?pending.reject(new Error(message.error)):pending.resolve(message.result)}}}
  prune(){const cutoff=Date.now()-this.heartbeatMs*3;for(const [id,p] of this.peers)if(p.at<cutoff)this.peers.delete(id)}
  snapshot(){return {id:this.id,capabilities:this.capabilities(),peers:[...this.peers.values()].map(p=>({id:p.id,capabilities:p.capabilities,handlers:p.handlers||[]}))}}
}
